#define IDLE_PULSE_WIDTH 20

#define TURNING_STAGE_LEFT 0
#define TURNING_STAGE_IDLE 1
#define TURNING_STAGE_RIGHT 2

#define THROTTLE_STAGE_AHEAD 3
#define THROTTLE_STAGE_BACK 4
#define THROTTLE_STAGE_IDLE 5

#define THROTTLE_PULSE_PIN 27
#define STEARING_PULSE_PIN 26